### ISSUE TITLE
Negative signup fees not working with Stripe

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Restrict-Content-Pro#212]
From a customer:

Trying to setup a $100 off the first year type subscription $390 - $100 = $290):
https://cloudup.com/cCrFtDRoe-X

Registration form shortcode:
https://cloudup.com/cYt9E57anhQ

Odd, registration form says $390 - no indication of first year discount?
https://cloudup.com/cm7cK0Z5zk0

Charge went through at $390, not $290!
https://cloudup.com/c7Uz9UC1-xM

Subscription cost is $390 as expected so that works.

**Comment by tnorthcutt** [comment]
Additional data point: on my local testing install, I at first tried this in Paypal Sandbox mode and was (as expected) not able to reproduce. Then, I switched Stripe on (in test mode), and was able to reproduce, as expected.

However, then I switched Stripe back off, to try and see how the Paypal Sandbox mode was getting the correct price, and was able to reproduce the problem there, too (getting a sandbox.paypal.com payment page with $390 instead of $290). Perhaps an anomaly, but maybe useful. I'll update when/if I'm able to dig further.

**Comment by pippinsplugins** [comment]
I've tracked this down, at least for Stripe.

**Comment by pippinsplugins** [comment]
@tnorthcutt Were you signing up for a recurring or one time with PayPal?

**Comment by pippinsplugins** [comment]
The signup fee only works for recurring subscriptions in PayPal standard.

**Comment by tnorthcutt** [comment]
@pippinsplugins I believe recurring, but I can try again if you need a repro.

**Comment by pippinsplugins** [comment]
@tnorthcutt if you do try it again and can replicate it, reopen this please.
